#if !canImport(ObjectiveC)
import XCTest

extension EntityIdentifiersPoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityIdentifiersPoolTests = [
        ("test_flush_method", test_flush_method),
        ("test_free_method", test_free_method),
        ("test_take_method", test_take_method),
    ]
}

extension EntityTraitSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityTraitSetTests = [
        ("test_match_one_excluded_method", test_match_one_excluded_method),
        ("test_match_one_required_method", test_match_one_required_method),
        ("test_match_two_excluded_method", test_match_two_excluded_method),
        ("test_match_two_required_method", test_match_two_required_method),
    ]
}

extension UnorderedSparseSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnorderedSparseSetTests = [
        ("test_contains_method", test_contains_method),
        ("test_count_and_isEmpty_properties", test_count_and_isEmpty_properties),
        ("test_get_method", test_get_method),
        ("test_insert_method", test_insert_method),
        ("test_removeAll_method", test_removeAll_method),
        ("test_search_method", test_search_method),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EntityIdentifiersPoolTests.__allTests__EntityIdentifiersPoolTests),
        testCase(EntityTraitSetTests.__allTests__EntityTraitSetTests),
        testCase(UnorderedSparseSetTests.__allTests__UnorderedSparseSetTests),
    ]
}
#endif
